name: Build LGL Mod Menu

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v2
      with:
        ndk-version: r25b
        android-version: 31

    - name: Run ndk-build
      run: |
        cd jni
        ${{ env.ANDROID_NDK_HOME }}/ndk-build

    - name: Upload Artifacts (.so files)
      uses: actions/upload-artifact@v4
      with:
        name: LGL-ModMenu-Libraries
        path: |
          libs/**/*.so
          obj/local/**/*.so
