name: Build LGL Mod Menu

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25b

    - name: Run ndk-build
      run: |
        MK_PATH=$(find . -name "Android.mk" | head -n1)
        if [ -z "$MK_PATH" ]; then
          echo "Không tìm thấy file Android.mk trong repo"
          exit 1
        fi
        PROJECT_PATH=$(dirname "$(dirname "$MK_PATH")")
        echo "Android.mk: $MK_PATH"
        echo "NDK_PROJECT_PATH: $PROJECT_PATH"
        ndk-build NDK_PROJECT_PATH="$PROJECT_PATH"

    - name: Upload Artifacts (.so files)
      uses: actions/upload-artifact@v4
      with:
        name: LGL-ModMenu-Libraries
        path: |
          libs/**/*.so
          obj/local/**/*.so
